### ISSUE TITLE
Tooks to long for start

### ISSUE THREAD

**Issue by FDiskas** [iJackUA/try-yii2#5]
There is no progress looks like stuck in the middle of something
```
==> default: TASK: [phpredis | install PhpRedis for php lower than 5.5 (5.3 - 5.4)] ******** 
==> default: skipping: [vagrant]
==> default: 
==> default: TASK: [redis | download Redis] ************************************************ 
==> default: skipping: [vagrant]
```

**Comment by iJackUA** [comment]
Checked it. Due to some Ansible terminal output buffering issues it is just taking more time to display further progress. But everything seems to work fine at this step. Just wait :)
